# Generated by Django 3.0.2 on 2020-02-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0004_akash'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehnumber', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('modnumber', models.CharField(max_length=200)),
                ('permitdate', models.CharField(max_length=200)),
                ('licensen', models.CharField(max_length=200)),
                ('averg', models.CharField(max_length=200)),
                ('rc', models.CharField(max_length=200)),
                ('tank', models.CharField(max_length=200)),
                ('transp', models.CharField(max_length=200)),
                ('dnumber', models.CharField(max_length=200)),
                ('pic', models.CharField(max_length=200)),
            ],
        ),
    ]
