# Generated by Django 3.0.2 on 2020-02-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0007_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='pword',
            field=models.CharField(default='', max_length=200),
        ),
    ]
